### ISSUE TITLE
flagpole add suite - Scenario Start Path can't start with /

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#22]
## Expected Behavior

`flagpole add suite` command should accept `/` or `/xxxx` as a Scenario Start Path

## Actual Behavior

Error message `Please Enter A Valid Value` in command line, refusal to move forward.
You can proceed by entering a string that does not start with `/`.
Environments in VSCode's terminal and MacOS standalone Terminal.

## Steps to Reproduce the Problem

  1. `flagpole add suite`
  2. Hit enter 5 times to accept default values
  3. Observe error message

## Specifications

  - Flagpole: 2.2.12
  - VSCode: 1.44.2
  - Node.js : 12.8.1
  - Terminal: 2.10

![Screen Shot 2020-04-23 at 4 46 16 PM](https://user-images.githubusercontent.com/46609057/80147834-1b63f600-8582-11ea-8804-2649e7932c4b.png)

**Comment by jasonbyrne** [comment]
Reproduced. This is a different bug than before. On it.

**Comment by jasonbyrne** [comment]
Fixed on my machine. Will publish update tonight. v2.2.13
