### ISSUE TITLE
.comment only accepts a string

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#30]
Feature request to allow `.comment` method to have some type coercion similar to how `console.log` handles data.

I often get errors like
`error TypeError: Converting circular structure to JSON`

Or 
`Type 'iValue[]' is not assignable to type 'string'.`

And have to use `.toString()` more than I'd like

and then ultimate falling back to `console.log`

Thank you :-)

**Comment by jasonbyrne** [comment]
this will be in v2.3.9
