### ISSUE TITLE
.click() confirmation

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#31]
Right now if you click, but the element doesn't exist, nothing happens.

I'm wondering if we could get some sort of confirmation or notice that the element has been clicked/doesn't exist.

Small repro:

```
suite
  .browser("Click on element that doesn't exist")
  .open("https://stackoverflow.com/")
  .next(async (context) => {
    context.click("a.login-linc");
    await context.waitForNavigation();
  });
```

Will fail on 
`✕  TimeoutError: Navigation timeout of 10000 ms exceeded`

When in fact, it's not a navigation error, but a spelling error:

`"a.login-linc"` -> `"a.login-link"`

**Comment by jasonbyrne** [comment]
Good idea. This will be in the next update
