### ISSUE TITLE
Run multiple suites with -s only runs the first suite

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#42]
Expected behavior:
`flagpole run -s suiteA suiteB`
Will run both suites

Actual activity:
Only runs suiteA

https://flocasts.github.io/flagpole/#/cli?id=-s-suitename

Version: 2.4.9

**Comment by jasonbyrne** [comment]
this should already work with comma-separated suite names, not spaces

**Comment by jasonbyrne** [comment]
John updated the documentation
