### ISSUE TITLE
Dependency issue with fs-extra

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#44]
This is a screenshot of my CircleCI build failing on an unexpected token from fs-extra. Cannot reproduce local. 

Here, others are experiencing similar issues in Cloud Build, maybe others.. 
https://github.com/vercel/pkg/issues/883

<img width="1129" alt="Screen Shot 2020-06-09 at 5 25 48 PM" src="https://user-images.githubusercontent.com/46609057/84202385-447b1000-aa76-11ea-9470-876d447c3953.png">

Recommendation is to possibly roll back fs-extra to version 8..?

Node version 13.8.0
Flagpole version 2.4.9

**Comment by alexanderbelokon-mway** [comment]
Same for me

**Comment by jasonbyrne** [comment]
I haven't been able to reproduce this yet. Trying.

**Comment by jasonbyrne** [comment]
Appears to be related to this: https://github.com/jprichardson/node-fs-extra/pull/794

https://www.codespot.org/javascript-es2019-optional-catch-binding/

I'm not sure if there is anything I can do except strip out fs-extra

**Comment by johnsickels** [comment]
Going to close as I haven't seen this lately
