### ISSUE TITLE
Ability to run flagpole commands without interaction

### ISSUE THREAD

**Issue by jordangarrison** [flocasts/flagpole#46]
The particular command I have in mind for this is the `flagpole add env` command. What this would allow the user to do is during the CI pipeline if they have a generated URL for their service, it will not be located in the `flagpole.json` file. This requires template syntax inside the `flagpole.json` (a little bit of a hack) file or updating all the tests to use `process.env.URL_ENV_VAR` (a lot of extra typing) to allow for URL generation of a preview environment.

If instead we could support running the command like this: `flagpole add env [[env-name] [url-for-env]]` where the `env-name` and `url-for-env` are optional parameters for the command which if not given will allow for the user to fill it in (see this example in [LTP](https://github.com/flocasts/load-testing-platform/blob/infra-2296-ltp-api/src/cmds/run.cmd.ts#L34-L36) which is a little dirty but presents the concept).

**Comment by jasonbyrne** [comment]
@jordangarrison This will be added in version 2.4.11 and the command will be like this:

flagpole add env --label pv --url https://www.dev.com

If the "pv" environment already exists it will update it.
