### ISSUE TITLE
Flagpole requires npm ajv

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#49]
Try to `flagpole build`:

```../node_modules/flagpole/dist/interfaces.d.ts(8,22): error TS2307: Cannot find module 'ajv'.```

Flagpole versions 2.4.10 through 2.4.14

**Comment by jordangarrison** [comment]
I can confirm that this also happens in my repo but throws `cannot find module 'puppeteer'` recently updated to version 2.3 and made no code changes from prior working builds.

In the meantime I installed the dev dependency

**Comment by jasonbyrne** [comment]
This was fixed previously
