### ISSUE TITLE
Minikin Invalid character error on flagpole build command

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#55]
`flagpole build`

fails on 

```                                                                                  
Transpiling TypeScript to JavaScript...
../node_modules/minikin/dist/afterware.d.ts(6,5): error TS1127: Invalid character.
../node_modules/minikin/dist/handler.d.ts(6,5): error TS1127: Invalid character.
../node_modules/minikin/dist/response.d.ts(6,5): error TS1127: Invalid character.
../node_modules/minikin/dist/router.d.ts(7,5): error TS1127: Invalid character.
../node_modules/minikin/dist/server.d.ts(5,5): error TS1127: Invalid character.
```

Looking closer at these lines...
```
    #private;
```

My guess is that TypeScript is unhappy with the `#`. I tried adding node_modules to the exclude property of `tsconfig.json`. 

VSCode TypeScript version 4.0.2
NPM TypeScript Version 3.7.5
Flagpole versions >2.5.9

**Comment by jasonbyrne** [comment]
Probably because of the NPM version of TypeScript the # character was added in one of the newer TS versions. Try upgrading tsc.

**Comment by jasonbyrne** [comment]
Or upgrading node

**Comment by johnsickels** [comment]
Upgrading typescript globally fixed it. Thank you!
