### ISSUE TITLE
Assert undefined is string passes

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#63]
```
.assert('undefined is string', undefined).is.string();
```

This is a passing assertion

v2.5.26

**Comment by jasonbyrne** [comment]
I can repro this. Looking into fix

**Comment by jasonbyrne** [comment]
Ahhh... because when the second argument is `undefined` it thinks you didn't set the second argument... so the overloading sets the value of your assertion as `"undefined is string"` (which is a string). I need to think about this one... hmmm..

**Comment by jasonbyrne** [comment]
ok got it fixed by testing for `arguments.length === 2` instead. will be in next update
