### ISSUE TITLE
Browser scenario dangles on insecure request

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#64]
## The problem
A request to an insecure endpoint fails to finish on browser scenarios

## Expected 
Maybe a soft error, or no error at all

## Repro
```
import flagpole from "flagpole";

const suite = flagpole("Basic Smoke Test of Site");

suite
  .scenario("Homepage Loads", "browser")
  .open("https://www.jasonbyrne.net")
  .next(async (context) => {
    await context.exists("h1");
  });
```
## Note
You must include www for this to dangle. Any request to `https://jasonbyrne.net` or `http://jasonbyrne.net` will succeed. 
I actually came across this error when the base url is set in `flagpole.json`:
```
"info": {
  "name": "info",
  "defaultDomain": "https://www.milesplit.info"
},
```
And provide only the path in the test suite:
```
suite
  .browser("Login Page Loads")
  .setBasicAuth(basicAuth)
  .open("/login")
  ```

**Comment by jasonbyrne** [comment]
Thanks for the repro. Working on this

**Comment by jasonbyrne** [comment]
Fixed in the next version
