### ISSUE TITLE
Image scenario 

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#65]
I'm getting weird output on an image scenario and don't know why. It happens sporadically, and often fails to repeat itself on a test retry. Any ideas what it could be or any error handling we could implement to provide a more useful message?

```
/service/node_modules/@zerodeps/image-probe/dist/PngProbe.js:17 return buffer.length >= MINIMUM_BUFFER_LENGTH && ^ TypeError: Cannot read property 'length' of null at PngProbe.probeType (/service/node_modules/@zerodeps/image-probe/dist/PngProbe.js:17:23) at Function.fromBuffer (/service/node_modules/@zerodeps/image-probe/dist/index.js:15:23) at PassThrough.
(/service/node_modules/flagpole/dist/httprequest.js:370:46) at PassThrough.emit (events.js:314:20) at emitReadable_ (_stream_readable.js:557:12) at processTicksAndRejections (internal/process/task_queues.js:83:21)
Completed 3/8/2021, 4:30:10 PM EST
```

**Comment by johnsickels** [comment]
Actually, I got one:

Seems like any non-200 response to an image will produce this error:

404
http://www.milesplit.com/image.png

403
http://foobar.com/baz.jpg

The requests I usually see the failure on are from cloudfront:
https://dx5a7fcdm93g5.cloudfront.net/streams/13535/images/tiles_320x180_1613750410328_1613754010328_0001.jpg

I'm most confused because a retry will succeed.. May have to "probe" a bit more into my use case..

Anyway here's the repro:

```
import flagpole from "flagpole";

const suite = flagpole("Basic Smoke Test of Image");

suite
  .scenario("Image Loads", "image")
  .open("http://foobar.com/baz.jpg")
  .next(async (context) => {
    context.assert(context.response.statusCode).equals(200);
  });
```

**Comment by jasonbyrne** [comment]
This was fixed in a previous update.
