### ISSUE TITLE
Create an index that would allow multiple imports from flagpole

### ISSUE THREAD

**Issue by AlexPierce18** [flocasts/flagpole#9]
Right now, when you import Suite, Scenario etc., the import points directly to the specific file like this: import { Scenario } from 'flagpole/dist/scenario';

It would be nice to have an index that would allow us to do something like this:
import { Suite , Scenario } from 'flagpole';

**Comment by jasonbyrne** [comment]
Great idea! Will make it happen.

**Comment by jasonbyrne** [comment]
This is resolved in 2.0.26
